# Change these first
owner: UQ-RCC # Your GitHub organization or username, where this repository lives
repo: portals # The name of this repository

sites:
  - name: RCC auth
    url: $AUTH_RCC_URL
    maxResponseTime: 5000
    assignees:
      - markendr
      - hoangnguyen177
  - name: IPP
    url: $IPP_URL
    maxResponseTime: 5000
    assignees:
      - markendr
      - hoangnguyen177
  - name: IPP pref version
    url: $IPP_PREF_URL
    maxResponseTime: 5000
    assignees:
      - markendr
      - hoangnguyen177
  - name: Pitschi
    url: $PITSCHI_URL
    maxResponseTime: 5000
    assignees:
      - markendr
      - hoangnguyen177
  - name: Pitschi XAPI user
    method: GET
    url: $PITSCIH_XAPI_USER_URL
    maxResponseTime: 5000
    headers:
      - "Authorization: Basic $PITSCIH_XAPI_BEARER_TOKEN"
      - "accept: application/json"
    assignees:
      - markendr
      - hoangnguyen177
  - name: Pitschi XAPI1 user
    method: GET
    url: $PITSCHI_XAPI1_HELLO
    maxResponseTime: 5000
    headers:
      - "accept: application/json"
    assignees:
      - markendr
      - hoangnguyen177
  - name: Pitschi XAPI2 user
    method: GET
    url: $PITSCHI_XAPI2_HELLO
    maxResponseTime: 5000
    headers:
      - "accept: application/json"
    assignees:
      - markendr
      - hoangnguyen177
  - name: XNAT
    url: $XNAT_URL
    maxResponseTime: 5000
    assignees:
      - markendr
      - aswinnarayanan
  - name: RCC Packages Repo
    method: GET
    url: https://packages.rcc.uq.edu.au/ubuntu/
    maxResponseTime: 5000
  - name: Nimrod Portal
    method: GET
    url: https://nimrod.rcc.uq.edu.au/
    maxResponseTime: 5000
  - name: Legacy IMB Portal
    method: GET
    url: https://imbmicroscopy.rcc.uq.edu.au/
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uq-rcc.github.io
  baseUrl: /portals
  logoUrl: https://avatars.githubusercontent.com/u/29138696?s=400&u=b56f5d2be37ac991cd6703fc7e9aad0ac4d9cba6&v=4
  name: Upptime for ipp and pitschi
  introTitle: "**Upptime** for RCC portals."
  introMessage: "" 
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
